name: Deploy to Prod

on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: npm install
      - name: Run tests
        run: npm test
  production:
    if: ${{ github.event_name == 'workflow_dispatch' && github.ref_name == 'main' }}
    env:
      environment: production
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: tests
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm install
      - name: Environment
        run: |
          echo "Environment: $ENVIRONMENT"
        env:
          NAME: ${{ env.name }}
          ENVIRONMENT: ${{ env.environment }}
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: publish --env ${{ env.environment }}
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}