name: Test PR to Develop

on:
  pull_request:
    branches:
      - develop

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: npm install
      - name: Run tests
        run: npm test